name: Get quotes

on:
  workflow_dispatch:

permissions: write-all

jobs:
  get-quotes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          curl -s https://www.fondidoc.it/Chart/ChartData\?ids\=SAZINTE%3BBSCI203\&cur\=EUR | \
          jq '.SAZINTE.data[] | {date: ((.[0]) * 100), close: .[1]}' | jq -s > eurizon.json
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Automated report"
          git push
